<a href="https://colab.research.google.com/github/jananilakshminarayanan/DA-DS-projects/blob/main/ML_casestudy_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
import numpy as np

stop_words = set(stopwords.words("english")) # to get distinct unique words only from stopwords


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# function which returns all words present in a sentence by first removing stopwords and making all to lower cases
# returns list of text words
def extract_words(sentence):
    cleaned_text = [w.lower() for w in nltk.word_tokenize(sentence) if w not in stop_words ]
    return cleaned_text


In [ ]:
# function which takes a list of sentences as argument and return a list of unique words present in that
def vocab(corpus):
    vocabulary = []

    # list of words in the corpus
    for doc in corpus:
        word = extract_words(doc)
        vocabulary.extend(word)

    # find unique words in vocabulary list and sort them alphabetically
    vocabulary = sorted(list(set(vocabulary)))
    return vocabulary


In [ ]:
# function which creates a bag of words model which returns word count vector for any input sentence
def bag_of_words(sentence, vocabulary):

    words = extract_words(sentence)

    # creates a numpy array the length of no of words in vocabulary and fill it with zeros
    bag = np.zeros(len(vocabulary))

    for word in words:
        # check whether word is present in vocabulary list
        for i, vocab in enumerate(vocabulary):
            if vocab == word:
                bag[i] += 1 # if word is present in vocabulary change 0 to 1

    return np.array(bag) # converting enumerate obj to np array

In [ ]:
corpus = ["Once, there was a boy who became bored when he watched over the village sheep grazing on the hillside.",
          "To entertain himself, he sang out Wolf Wolf! The wolf is chasing the sheep! ",
          "When the villagers heard the cry, they came running up the hill to drive the wolf away.",
          "But, when they arrived, they saw no wolf.", "The boy was amused when seeing their angry faces."]

In [ ]:
vocabulary = vocab(corpus)
print("Vocabulary: \n", vocabulary)

Vocabulary: 
 ['!', ',', '.', 'amused', 'angry', 'arrived', 'away', 'became', 'bored', 'boy', 'but', 'came', 'chasing', 'cry', 'drive', 'entertain', 'faces', 'grazing', 'heard', 'hill', 'hillside', 'once', 'running', 'sang', 'saw', 'seeing', 'sheep', 'the', 'to', 'village', 'villagers', 'watched', 'when', 'wolf']


In [ ]:
bag_of_words("video showing villagers chasing away wild elephants have amused many who watched it ", vocabulary)

array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.])

In [ ]:
# bag of words using scikit library
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [ ]:
text_data = np.array(["Once, there was a boy who became bored when he watched over the village sheep grazing on the hillside.",
          "To entertain himself, he sang out Wolf Wolf! The wolf is chasing the sheep! ",
          "When the villagers heard the cry, they came running up the hill to drive the wolf away.",
          "But, when they arrived, they saw no wolf.", "The boy was amused when seeing their angry faces."])

In [ ]:
count = CountVectorizer()

bag_of_words = count.fit_transform(text_data)

# show feature mmatrix
bag_of_words.toarray()

array([[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]],
      dtype=int64)

In [ ]:
# get feature names
feature_names = count.get_feature_names()

feature_names

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['amused',
 'angry',
 'arrived',
 'away',
 'became',
 'bored',
 'boy',
 'but',
 'came',
 'chasing',
 'cry',
 'drive',
 'entertain',
 'faces',
 'grazing',
 'he',
 'heard',
 'hill',
 'hillside',
 'himself',
 'is',
 'no',
 'on',
 'once',
 'out',
 'over',
 'running',
 'sang',
 'saw',
 'seeing',
 'sheep',
 'the',
 'their',
 'there',
 'they',
 'to',
 'up',
 'village',
 'villagers',
 'was',
 'watched',
 'when',
 'who',
 'wolf']

In [ ]:
# represent as dataframe
pd.DataFrame(bag_of_words.toarray(), columns=feature_names)

amused  angry  arrived  away  became  bored  boy  but  came  chasing  ...  \
0       0      0        0     0       1      1    1    0     0        0  ...   
1       0      0        0     0       0      0    0    0     0        1  ...   
2       0      0        0     1       0      0    0    0     1        0  ...   
3       0      0        1     0       0      0    0    1     0        0  ...   
4       1      1        0     0       0      0    1    0     0        0  ...   

   they  to  up  village  villagers  was  watched  when  who  wolf  
0     0   0   0        1          0    1        1     1    1     0  
1     0   1   0        0          0    0        0     0    0     3  
2     1   1   1        0          1    0        0     1    0     1  
3     2   0   0        0          0    0        0     1    0     1  
4     0   0   0        0          0    1        0     1    0     0  

[5 rows x 44 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
text_data = np.array(["Once, there was a boy who became bored when he watched over the village sheep grazing on the hillside.",
          "To entertain himself, he sang out Wolf Wolf! The wolf is chasing the sheep! ",
          "When the villagers heard the cry, they came running up the hill to drive the wolf away.",
          "But, when they arrived, they saw no wolf.", "The boy was amused when seeing their angry faces."])

In [ ]:
tfid_vector = TfidfVectorizer(stop_words = stop_words)

tfidvectors = tfid_vector.fit_transform(text_data)
tfidvectors.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.37007017,
        0.37007017, 0.29857028, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.37007017, 0.        ,
        0.        , 0.37007017, 0.        , 0.        , 0.        ,
        0.        , 0.29857028, 0.37007017, 0.        , 0.37007017,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.36066693, 0.        ,
        0.        , 0.36066693, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.36066693, 0.        ,
        0.        , 0.29098381, 0.        , 0.        , 0.        ,
        0.72462854],
       [0.        , 0.        , 0.        , 0.34404072, 0.        ,
        0.        , 0.        , 0.34404072, 0.        , 0.34404072,
        0.34404072, 0.        , 0.        , 0.        , 0.34404072,
        0.34404072, 0.        , 0.34404072, 0.        , 0.        ,
      

In [ ]:
feature_names = tfid_vector.get_feature_names()
feature_names

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['amused',
 'angry',
 'arrived',
 'away',
 'became',
 'bored',
 'boy',
 'came',
 'chasing',
 'cry',
 'drive',
 'entertain',
 'faces',
 'grazing',
 'heard',
 'hill',
 'hillside',
 'running',
 'sang',
 'saw',
 'seeing',
 'sheep',
 'village',
 'villagers',
 'watched',
 'wolf']

In [ ]:
pd.DataFrame(tfidvectors.toarray(), columns=feature_names)

amused     angry  arrived      away   became    bored       boy  \
0  0.000000  0.000000  0.00000  0.000000  0.37007  0.37007  0.298570   
1  0.000000  0.000000  0.00000  0.000000  0.00000  0.00000  0.000000   
2  0.000000  0.000000  0.00000  0.344041  0.00000  0.00000  0.000000   
3  0.000000  0.000000  0.63907  0.000000  0.00000  0.00000  0.000000   
4  0.463693  0.463693  0.00000  0.000000  0.00000  0.00000  0.374105   

       came   chasing       cry  ...  hillside   running      sang      saw  \
0  0.000000  0.000000  0.000000  ...   0.37007  0.000000  0.000000  0.00000   
1  0.000000  0.360667  0.000000  ...   0.00000  0.000000  0.360667  0.00000   
2  0.344041  0.000000  0.344041  ...   0.00000  0.344041  0.000000  0.00000   
3  0.000000  0.000000  0.000000  ...   0.00000  0.000000  0.000000  0.63907   
4  0.000000  0.000000  0.000000  ...   0.00000  0.000000  0.000000  0.00000   

     seeing     sheep  village  villagers  watched      wolf  
0  0.000000  0.298570  0.37007   0.000000  0.37007  0.000000  
1  0.000000  0.290984  0.00000   0.000000  0.00000  0.724629  
2  0.000000  0.000000  0.00000   0.344041  0.00000  0.230408  
3  0.000000  0.000000  0.00000   0.000000  0.00000  0.427993  
4  0.463693  0.000000  0.00000   0.000000  0.00000  0.000000  

[5 rows x 26 columns]